### ISSUE TITLE
Magento 2.4.3 support

### ISSUE THREAD

**Issue by arjunadobe** [BoltApp/bolt-magento2#1371]
Hi,
We are upgrading our site from Magento 2.4.2-p1 to Magento 2.4.3. We are facing the issue while running the site and we got the below error. 

Class Zend\Serializer\Adapter\PhpSerialize does not exist

It looks like the below modules are removed in 2.4.3 and because of this we are facing the error. 

  - Removing laminas/laminas-serializer (2.10.0)
  - Removing laminas/laminas-psr7bridge (0.2.2)
  - Removing laminas/laminas-log (2.12.0)
  - Removing laminas/laminas-inputfilter (2.10.1)
  - Removing laminas/laminas-hydrator (2.4.2)
  - Removing laminas/laminas-form (2.15.1)
  - Removing laminas/laminas-diactoros (1.8.7p2)
  - Removing laminas/laminas-console (2.8.0)

**Comment by vitaliyreznikov** [comment]
Thank you for your request @arjunadobe!
We are working on this issue and we will include support for 2.4.3 to one of our next plugin versions.
If you have any questions please reach out to our support team. https://support.bolt.com/
