### ISSUE TITLE
Magento marketplace installation error

### ISSUE THREAD

**Issue by brunogemelli** [BoltApp/bolt-magento2#1485]
I am getting the error below when trying to update the module:

> [Exception] Higher matching version 2.24.1 of boltpay/bolt-magento2 was found in public repository packagist.org than 2.24.0 in private https://repo.magento.com. Public package might've been taken over by a malicious entity, please investigate and update package requirement to match the version from the private repo story

Will you push to the Magento Marketplace the latest version (2.24.1)?

**Comment by danac-gs** [comment]
@BoltApp/commerce-platform can you resolve this?

**Comment by vitaliyreznikov** [comment]
@brunogemelli 2.24.1 in  https://repo.magento.com is not approved yet.
Please reach out to our support support@bolt.com if you would like us to inform you once the release is approved
