### ISSUE TITLE
Magento 2.4.6

### ISSUE THREAD

**Issue by kennyminsight** [BoltApp/bolt-magento2#1779]
After upgrading to Magento 2.4.6. When we go to the checkout page, we get  an error 
`Validate class not found from basename 'Magento\Framework\Validator\EmailAddress'`
from the request 
` /customer/section/load/?sections=boltcart&force_new_section_timestamp=true&_=1679672819188. `
It looks like Zend_Validate was replaced with laminas-validator. Is there an updated version of Bolt Pay for Magneto 2.4.6.

**Comment by kennyminsight** [comment]
We are currently running version boltpay/bolt-magento2 2.26.5 after upgrading via composer.

**Comment by vitaliyreznikov** [comment]
Hi Kenny! Thank you for raising this! We fixed compatibility with Magento 2.4.6 in the latest bolt version - 2.27.1.
