### ISSUE TITLE
Bolt pay doubling total after update to Magento 2.4.6p2

### ISSUE THREAD

**Issue by Celiars** [BoltApp/bolt-magento2#1849]
We are seeing a strange issue after updating Magento to 2.4.6p2 from 2.4.6 (bolt-magento2  is on 2.27.2). Everything that is charged is correct, but the total paid is double the grand total. Can you please advise.

**Comment by vitaliyreznikov** [comment]
Hi Celia! Could you please send your request via our support?
support@bolt.com
