### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by mtjweb** [BoltApp/bolt-magento2#761]
I tried to install this module today, but got the following error:

PHP Fatal error:  Uncaught Error: Class 'BolCom\RetailerApi\Model\ClientPoolInterface' not found in ../app/code/BolCom/Retailer/Setup/InstallSchema.php:79
Stack trace:
#0 ../app/code/BolCom/Retailer/Setup/InstallSchema.php(27): BolCom\Retailer\Setup\InstallSchema->createEntityLinkTable(Object(Magento\Setup\Module\Setup))
#1../setup/src/Magento/Setup/Model/Installer.php(1000): BolCom\Retailer\Setup\InstallSchema->install(Object(Magento\Setup\Module\Setup), Object(Magento\Setup\Model\ModuleContext))
#2 ../setup/src/Magento/Setup/Model/Installer.php(839): Magento\Setup\Model\Installer->handleDBSchemaData(Object(Magento\Setup\Module\Setup), 'schema', Array)
#3../setup/src/Magento/Setup/Console/Command/UpgradeCommand.php(122): Magento\Setup\Model\Installer->installSchema(Array)
#4 ../vend in ../app/code/BolCom/Retailer/Setup/InstallSchema.php on line 79

I downloaded the files on marketplace.magento.com and uploaded them in het /app/code/BolCom/Retailer/folder.
I then ran php bin/magento setup:upgrde command and got this error.

I'm running Magento 2.3.5-p1

**Comment by adentong** [comment]
@njfaries @matt-thomason you guys see this?

**Comment by mccottry** [comment]
@adentong `BolCom` has nothing to do with Bolt.

It seems that either the reporter confused companies or they have an additional module that they are trying to install that has problems.
